version: "3.9"

services:
  db:
    image: wedsel2/docker-workshop-db
    environment:
      POSTGRES_DB: moviereviews
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppass

  web:
    image: wedsel2/docker-workshop-webapp
    depends_on:
      - db
    environment:
      DB_HOST: db
    ports:
      - "8000:8000"
