CREATE TABLE IF NOT EXISTS reviews (
    id SERIAL PRIMARY KEY,
    movie_title VARCHAR(255) NOT NULL,
    reviewer VARCHAR(100) NOT NULL,
    rating INTEGER NOT NULL CHECK (rating BETWEEN 1 AND 10),
    review_text TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

TRUNCATE TABLE reviews RESTART IDENTITY;

INSERT INTO reviews (movie_title, reviewer, rating, review_text) VALUES
('The Godfather', 'Alex', 10, 'A timeless crime drama with incredible performances.'),
('The Dark Knight', 'Jordan', 10, 'A gripping superhero film elevated by a legendary villain.'),
('Pulp Fiction', 'Casey', 9, 'Sharp dialogue, nonlinear storytelling, and unforgettable scenes.'),
('Inception', 'Taylor', 9, 'A smart and visually stunning sci-fi heist movie.'),
('The Shawshank Redemption', 'Morgan', 10, 'An uplifting story about hope and friendship.'),
('Interstellar', 'Riley', 9, 'Emotion and science blend beautifully in this space epic.'),
('Parasite', 'Jamie', 10, 'Brilliant social satire with perfect pacing and tension.'),
('Whiplash', 'Drew', 9, 'Intense, focused, and powered by two great performances.'),
('Mad Max: Fury Road', 'Avery', 9, 'Relentless action with stunning practical effects.'),
('The Matrix', 'Parker', 9, 'Groundbreaking visuals and a thought-provoking premise.'),
('Gladiator', 'Quinn', 8, 'Epic scale and emotional weight make it memorable.'),
('Fight Club', 'Reese', 8, 'Provocative and stylish with a bold narrative voice.'),
('The Social Network', 'Skyler', 9, 'Fast, witty, and brilliantly directed.'),
('La La Land', 'Cameron', 8, 'A heartfelt modern musical with strong chemistry.'),
('The Silence of the Lambs', 'Harper', 9, 'Tense and expertly acted psychological thriller.'),
('No Country for Old Men', 'Blake', 9, 'Bleak, suspenseful, and masterfully crafted.'),
('The Lord of the Rings: The Fellowship of the Ring', 'Dakota', 9, 'A magical and immersive beginning to an epic trilogy.'),
('The Lord of the Rings: The Two Towers', 'Emerson', 9, 'Expands the world with scale and emotional stakes.'),
('The Lord of the Rings: The Return of the King', 'Finley', 10, 'A powerful and satisfying finale.'),
('Toy Story', 'Hayden', 8, 'Inventive animation and a lot of heart.'),
('Toy Story 3', 'Indigo', 9, 'Emotional storytelling that resonates across ages.'),
('Spider-Man: Into the Spider-Verse', 'Jules', 10, 'Inventive animation style and a joyful story.'),
('Coco', 'Kai', 9, 'Vibrant visuals and a touching family narrative.'),
('Inside Out', 'Logan', 9, 'Creative and emotionally intelligent storytelling.'),
('The Lion King', 'Marley', 8, 'Classic songs and memorable characters.'),
('The Prestige', 'Nico', 9, 'A clever rivalry drama with a great twist.'),
('Memento', 'Oakley', 8, 'A bold structure that rewards attention.'),
('The Departed', 'Phoenix', 9, 'Tense crime thriller with a stellar ensemble.'),
('Goodfellas', 'River', 9, 'Energetic and immersive mob storytelling.'),
('Se7en', 'Sage', 8, 'Dark, atmospheric, and unforgettable ending.'),
('Blade Runner 2049', 'Tatum', 9, 'A visually breathtaking and thoughtful sequel.'),
('Arrival', 'Uma', 9, 'Elegant sci-fi with emotional depth.'),
('Dune', 'Val', 8, 'Ambitious world-building and striking cinematography.'),
('The Grand Budapest Hotel', 'Wren', 8, 'Whimsical style with precise comedic timing.'),
('Her', 'Xen', 8, 'Quietly moving exploration of love and technology.'),
('Moonlight', 'Yael', 9, 'Beautifully acted and deeply human.'),
('Get Out', 'Zane', 9, 'Sharp social commentary wrapped in suspense.'),
('Black Panther', 'Arden', 8, 'Strong characters and a culturally impactful story.'),
('Avengers: Endgame', 'Briar', 8, 'A crowd-pleasing culmination with emotional beats.'),
('The Avengers', 'Cleo', 8, 'Fun team dynamics and blockbuster energy.'),
('Casablanca', 'Devon', 9, 'Classic romance with iconic dialogue.'),
('12 Angry Men', 'Ellis', 10, 'A masterclass in dialogue and tension.'),
('Rear Window', 'Gray', 9, 'Suspenseful and inventive filmmaking.'),
('Psycho', 'Hollis', 8, 'A landmark thriller that still chills.'),
('The Truman Show', 'Ira', 9, 'Smart concept with emotional sincerity.'),
('Forrest Gump', 'Jaden', 8, 'Heartwarming journey through decades of history.'),
('The Green Mile', 'Kendall', 8, 'Poignant drama with strong performances.'),
('A Beautiful Mind', 'Lennon', 8, 'A compelling biographical drama.'),
('The Imitation Game', 'Micah', 8, 'Engaging historical story with solid acting.'),
('Oppenheimer', 'Noel', 9, 'Powerful, intense, and technically impressive.');

